filetype: colortest

detect:
    filename: "ColorTest$"

rules:
    - comment: "comment *.*"
    - type: "type *.*"
    - type.keyword: "type\\.keyword *.*"
    - type.other: "type\\.other *.*"
    - identifier: "identifier *.*"
    - identifier.var: "identifier\\.var *.*"
    - constant: "constant *.*"
    - constant.number: "constant\\.number *.*"
    - constant.string: "constant\\.string *.*"
    - constant.var: "constant\\.var *.*"
    - constant.string.char: "constant\\.string\\.char *.*"
    - statement: "statement *.*"
    - symbol: "symbol *.*"
    - symbol.operator: "symbol\\.operator *.*"
    - symbol.brackets: "symbol\\.brackets *.*"
    - symbol.tag: "symbol\\.tag *.*"
    - preproc: "preproc *.*"
    - function: "function *.*"
    - method: "method *.*"
    - method.other: "method\\.other *.*"
    - special: "special *.*"
    - underlined: "underlined *.*"
    - label: "label"
    - info: "info *.*"
    - error: "error *.*"
    - todo: "todo *.*"
    - statusline: "statusline *.*"
    - unfocused: "unfocused *.*"
    - tabbar: "tabbar *.*"
    - invisible-char: "invisible-char *.*"
    - line-number: "line-number *.*"
    - current-line-number: "current-line-number *.*"
    - gutter-error: "gutter-error *.*"
    - gutter-warning: "gutter-warning *.*"
    - cursor-line: "cursor-line *.*"
    - color-column: "color-column *.*"
    - selection: "selection *.*"
    - matchbrace: "matchbrace *.*"
    - markup-head: "markup-head *.*"
    - markup-bold: "markup-bold *.*"
    - markup-table: "markup-table *.*"
    - markup-url: "markup-url *.*"
    - markup-underlined: "markup-underlined *.*"
    - markup-italic: "markup-italic *.*"
