filetype: git-config

detect:
    filename: "git(config|modules)$|\\.git/config$"

rules:
    - type: "^[[:space:]]*[^=]*="
    - constant: "^[[:space:]]*\\[.*\\]$"
    - constant.string: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"
    - constant: "(?:true|false)"
    - comment: "^\\s*#"
    - constant.string.url: "(ftp(s)?|http(s)?|git|chrome)://[^ \\t\\'\"]+"
