filetype: html

detect:
    filename: "\\.(htm[l]?[45]?|tt|tmpl)$"
    header: "<!DOCTYPE html[45]?>"

rules:
    - error: "<[^!].*?>"
    - symbol.tag: "</?.+?/?>"
    - symbol.tag: "</?[A-Za-z0-9:]+/?[ >]"


    - statement: "(?i)<[/]?(a|a(bbr|ddress|rea|rticle|side|udio)|b|b(ase|d(i|o)|lockquote|r|utton)|ca(nvas|ption)|center|cite|co(de|l|lgroup)|d(ata|atalist|d|el|etails|fn|ialog|l|t)|em|embed|fieldset|fig(caption|ure)|form|iframe|h[1-6]|hr|i|img|in(put|s)|kbd|keygen|label|legend|li|link|ma(in|p|rk)|menu|menuitem|met(a|er)|nav|noscript|o(bject|l|pt(group|ion)|utput)|p|param|picture|pre|progress|q|r(p|t|uby)|s|samp|se(ction|lect)|small|source|span|strong|su(b|p|mmary)|textarea|time|track|u|ul|var|video|wbr)( .*)*?>"
    - type: "(?i)<[/]?(body|div|html|head(er)?|footer|title|table|t(body|d|h(ead)?|r|foot))( .*)*?>"
    - constant.string: "\".*?\""
    - constant.string: "'.*?'"
    - special: "&[^;[[:space:]]]*;"
    - symbol: "[:=]"
    - identifier: "(alt|bgcolor|height|href|id|label|longdesc|name|on(click|focus|load|mouseover)|size|span|src|target|type|value|width|class)="
    - identifier: "data\\-.+?="
    - constant.number: "(?i)#[0-9A-F]{6,6}"
    - constant.tag: "&[\\w]{2,5};"
    - constant.string.url: "(ftp(s)?|http(s)?|git|chrome)://[^ 	]+"
    - comment: "<!--.+?-->"
    - info: "<!--\\w+: .+?-->"
    - todo: "<!--(?:todo|TODO): .+?-->"
    - error: "<!--(?:fix|FIX): .+?-->"
    - preproc: "<!DOCTYPE.+?>"

    - default:
        start: "<script.*?>"
        end: "</script.*?>"
        limit-group: symbol.tag
        rules:
            - include: "javascript"

    - default:
        start: "<style.*?>"
        end: "</style.*?>"
        limit-group: symbol.tag
        rules:
            - include: "css"

    - comment:
        start: "<!--$"
        end: "-->$"
        rules: []
