filetype: text

detect:
    filename: "\\.(text|txt)$"

rules:
    - constant.tag: "^[[:space:]]*[\\*\\-][[:space:]](?:[\\p{L}\\p{N}\\s]+)?$"
    - underlined: "[_\\-:=\\*]{3,}"
    - constant.string: "\".*?\""
    - constant.string: "'.*?'"
    - function: "^\\s*[\\p{L}\\p{N}\\s_\\-]+:"

